### ISSUE TITLE
can't run multiple RubyExpect sessions in one go

### ISSUE THREAD

**Issue by Nowaker** [abates/ruby_expect#2]
I really appreciate your work. This gem saved my life! Thanks.

All my tests that use RubyExpect pass when run separately. However, only the first test passes when I run all the tests. It looks like RubyExpect tries to reuse the spawned process (which no longer exists) instead of spawning a new one. Or it is no longer able to spawn any process. Hard to tell from the stacktrace.

```
PTY::ChildExited: pty - exited: 27224
/home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/ruby_expect-1.0/lib/ruby_expect/expect.rb:119:in `expect'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/ruby_expect-1.0/lib/ruby_expect/expect.rb:242:in `synchronize'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/ruby_expect-1.0/lib/ruby_expect/expect.rb:242:in `expect'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/ruby_expect-1.0/lib/ruby_expect/procedure.rb:98:in `run'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/ruby_expect-1.0/lib/ruby_expect/procedure.rb:97:in `each_index'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/ruby_expect-1.0/lib/ruby_expect/procedure.rb:97:in `run'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/ruby_expect-1.0/lib/ruby_expect/procedure.rb:176:in `each'
    lib/cisco/ssh_configurator.rb:36:in `execute'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/ruby_expect-1.0/lib/ruby_expect/procedure.rb:154:in `instance_eval'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/ruby_expect-1.0/lib/ruby_expect/procedure.rb:154:in `initialize'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/ruby_expect-1.0/lib/ruby_expect/expect.rb:167:in `new'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/gems/ruby_expect-1.0/lib/ruby_expect/expect.rb:167:in `procedure'
    lib/cisco/ssh_configurator.rb:35:in `execute'
    lib/cisco/ssh_configurator.rb:14:in `test_connection'
    test/unit/cisco/ssh_configurator_test.rb:9:in `test_test_SSH_connection_to_the_router'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/bundler/gems/rails-24a2aa124a93/activesupport/lib/active_support/testing/setup_and_teardown.rb:62:in `__send__'
    /home/nowaker/.rvm/gems/ruby-1.8.7-p374/bundler/gems/rails-24a2aa124a93/activesupport/lib/active_support/testing/setup_and_teardown.rb:62:in `run'
    (eval):12:in `run_suite'
    /opt/rubymine-eap/rb/testing/patch/testunit/test/unit/ui/teamcity/testrunner.rb:93:in `send'
    /opt/rubymine-eap/rb/testing/patch/testunit/test/unit/ui/teamcity/testrunner.rb:93:in `start_mediator'
    /opt/rubymine-eap/rb/testing/patch/testunit/test/unit/ui/teamcity/testrunner.rb:81:in `start'
```

This is my code:

```
  def execute is_configure, *commands
    ssh = RubyExpect::Expect.spawn("/usr/bin/ssh #@user@#@host", :debug => true)

    password = @password
    prompt = /ios#/

    ssh.procedure do
      each do
        expect /password:\s*$/ do
          send password
        end

        expect prompt do
          send 'terminal length 0' # don't use `more` for pagination
        end

        commands.each do |command|
          expect prompt do
            send command
          end
        end

        expect prompt do
          send 'exit'
        end
      end
    end

    ssh.output
  end
```

**Comment by abates** [comment]
Awhile back I rewrote the way IO works in this gem.  I believe this problem is now solved.  Closing

**Comment by Nowaker** [comment]
@abates Good to see numerous changes in the project. I'll happily try it out when I need to control SSH connection again. :) All the best!
