### ISSUE TITLE
More documentation on `interact` method?

### ISSUE THREAD

**Issue by netwolfuk** [abates/ruby_expect#8]
Hi, am pretty new to ruby, and am trying to get this Gem working with `ansible-vault`. My use case is that I want to run `ansible-vault` and then input the passphrase at the prompt.

The response from `ansible-vault` will be of an unknown length, which I want to then capture as a string. I have tried to use `expect` to handle the response in the following way.

```
  def xxdecrypt(encrypted_string)
    response = ""
    pass = @passphrase
    exp = RubyExpect::Expect.spawn(decrypt_command encrypted_string)
    exp.procedure do

      each do 
        expect /Vault password:/ do
          send pass
        end
      end

      retval = 0
      while (retval != 2)
        retval = any do
          expect /^[\S\s]+$/ do
            response << last_match.to_s
            send ""
          end          
        end
      end
    end
    puts response
```
And get the following error.
```
     RubyExpect::ClosedError:
       Read filehandle is closed
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/expect.rb:271:in `expect'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/procedure.rb:81:in `run'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/procedure.rb:165:in `any'
     # ./configuration/lib/ansible_vault.rb:137:in `block in xxdecrypt'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/procedure.rb:154:in `instance_eval'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/procedure.rb:154:in `initialize'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/expect.rb:197:in `new'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/expect.rb:197:in `procedure'
     # ./configuration/lib/ansible_vault.rb:127:in `xxdecrypt'
     # ./configuration/spec/ansible_vault_spec.rb:16:in `block (3 levels) in <top (required)>'
```

So I tried with `interact`
```
  def xdecrypt(encrypted_string)
    response = ""
    pass = @passphrase
    exp = RubyExpect::Expect.spawn(decrypt_command encrypted_string)
    exp.procedure do

      each do 
        expect /Vault password:/ do
          send pass
        end
      end

      exp.interact

      $stdout.each_line do |line|
        puts line
      end
```
This does dump out the response, I but I'm not able to capture it. Then it throws the following:
```
    Errno::EIO:
       Input/output error @ io_fillbuf - fd:7 /dev/pts/16
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/expect.rb:359:in `eof?'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/expect.rb:359:in `block in interact_loop'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/expect.rb:348:in `each'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/expect.rb:348:in `interact_loop'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/expect.rb:320:in `block in interact'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/expect.rb:319:in `raw'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/expect.rb:319:in `interact'
     # ./configuration/lib/ansible_vault.rb:68:in `block in xdecrypt'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/procedure.rb:154:in `instance_eval'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/procedure.rb:154:in `initialize'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/expect.rb:197:in `new'
     # ./vendor/bundle/ruby/2.5.0/gems/ruby_expect-1.7.4/lib/ruby_expect/expect.rb:197:in `procedure'
     # ./configuration/lib/ansible_vault.rb:60:in `xdecrypt'
     # ./configuration/spec/ansible_vault_spec.rb:16:in `block (3 levels) in <top (required)>'
```

Therefore, I thought I'd pass in the filehandle myself from popen3, but then the `expect` code is never executed. I'm doing...

```
  def decrypt(encrypted_string)
    pass = @passphrase
    i, o, e, t = Open3.popen3(decrypt_command encrypted_string)
      exp = RubyExpect::Expect.new(i, o)
      exp.expect(/Vault password:/) do
        puts pass
        send pass
      end
  end
```

As I say, I'm new to Ruby, so am probably doing something fundamentally wrong. 

Could you please show an example of using `interact`? 
Or would you suggest another way to use this Gem to accomplish what I am trying to achieve?

**Comment by abates** [comment]
Hi @netwolfuk, thanks for raising the issue.

We can definitely try to troubleshoot this, but you may want to try a different way to access the vault.  I use ruby to access an ansible vault as well, but I use this gem: [ansible-vault](https://rubygems.org/gems/ansible-vault)

here is how I use it:

```ruby
require "ansible/vault"
require "io/console"
require 'pwgen'
require "tempfile"
require "yaml"

module MyAnsible
  class Vault
    attr_accessor :content, :password

    def initialize
      @filename = "#{ENV['HOME']}/local/etc/ansible/group_vars/all/vault.yml"
      @content = nil
      while @content.nil?
        STDOUT.print "Vault password: "
        @password = STDIN.noecho(&:gets).strip
        STDOUT.puts

        begin
          @content = Ansible::Vault.read(path: @filename, password: @password)
        rescue Ansible::Vault::HMACMismatch => ex
          @content = nil
          STDERR.puts "Invalid password"
        end
      end
    end

    def to_hash
      YAML.load(@content)
    end

    def save!
      Ansible::Vault.write({path: @filename, password: @password, plaintext: @content})
    end
  end
end
```

If you really want to do this with ruby_expect let me know and I'll start troubleshooting.

**Comment by abates** [comment]
No worries.  Thanks!
